version: 2
formats: all
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
  system_packages: true
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
